### ISSUE TITLE
Data() method on Document interface

### ISSUE THREAD

**Issue by AnatoliiPrylutskyi** [augurysys/autocomplete#1]
Hi,

Can you please explain Data() method in Document interface?

Thanks

**Comment by bsphere** [comment]
I use the document's data to store additional information, such as database id that is returned with the search results, or "parent id" if you have dependencies between fields.. using an interface is for making it as general as it can be.

**Comment by AnatoliiPrylutskyi** [comment]
When I searching via Search method I always receiving jsons of document object. How can I info which I specified in Data() method?

**Comment by bsphere** [comment]
it depends on your implementation of the Document struct, make the fields exported (capital letter) and add json tags if necessary..
